### ISSUE TITLE
Detailed Population Tracking

### ISSUE THREAD

**Issue by chamons** [chamons/incremental-society#57]
Instead of our very simple "use log curve to trend to the effective population cap", can we model:

- Births
- Deaths
- Immigration
- Emigration

That will unlock more detail and cool things like "our health sucks, we are losing too many people to the plague"

- [x] Population needs determines health and happiness that affect growth
- [x] Happiness is based on luxury goods
- [x] UX breakdown of pop growth rate (with subcatagories), happiness, health

**Comment by chamons** [comment]
Something like:
```
Pop Delta = Pop * happy * c1 
+ happy * free housing * c2
- unhappy * pop * c3
- pop * health * c4
```
with c1-c4 are arbitrary constants.

This system gives us some nice things:
- We have a large resource dump, things to keep your population numbers up
- We have a place for happiness and health to affect things easily.
- We have multiple knobs to turn if we don't like curves.
